// 로그인 액션
export const UPDATE_USER = "UPDATE_USER";
export const UPDATE_USER_REQUEST = "UPDATE_USER_REQUEST";

export const SIGN_IN_WITH_GOOGLE_REQUEST = "SIGN_IN_WITH_GOOGLE_REQUEST";
export const SIGN_IN_WITH_GOOGLE_SUCCESS = "SIGN_IN_WITH_GOOGLE_SUCCESS";
export const SIGN_IN_WITH_GOOGLE_FAILED = "SIGN_IN_WITH_GOOGLE_FAILED";

export const SIGN_IN_WITH_FACEBOOK_REQUEST = "SIGN_IN_WITH_FACEBOOK_REQUEST";
export const SIGN_IN_WITH_FACEBOOK_SUCCESS = "SIGN_IN_WITH_FACEBOOK_SUCCESS";
export const SIGN_IN_WITH_FACEBOOK_FAILED = "SIGN_IN_WITH_FACEBOOK_FAILED";

export const SIGN_OUT_REQUEST = "SIGN_OUT_REQUEST";
export const SIGN_OUT_SUCCESS = "SIGN_OUT_SUCCESS";
export const SIGN_OUT_FAILED = "SIGN_OUT_FAILED";

//게시글 액션
export const ADD_ARTICLE_REQUEST = "ADD_ARTICLE_REQUSET";
export const ADD_ARTICLE_SUCCESS = "ADD_ARTICLE_SUCCESS";
export const ADD_ARTICLE_FAILED = "ADD_ARTICLE_FAILED";

export const GET_ARTICLE_LIST_REQUSET = "GET_ARTICLE_LIST_REQUEST";
export const GET_ARTICLE_LIST_SUCCESS = "GET_ARTICLE_LIST_SUCCESS";
export const GET_ARTICLE_LIST_FAILED = "GET_ARTICLE_LIST_FAILED";

export const GET_ARTICLE_REQUEST = "GET_ARTICLE_REQUEST";
export const GET_ARTICLE_SUCCESS = "GET_ARTICLE_SUCCESS";
export const GET_ARTICLE_FAILED = "GET_ARTICLE_FAILED";
export const GET_ARTICLE_RESET = "GET_ARTICLE_RESET";

export const CHANGE_SHOW_ARTICLE = "CHANGE_SHOW_ARTICLE";

export const DELETE_ARTICLE_REQUEST = "DELETE_ARTICLE_REQUEST";
export const DELETE_ARTICLE_SUCCESS = "DELETE_ARTICLE_SUCCESS";
export const DELETE_ARTICLE_FAILED = "DELETE_ARTICLE_FAILED";

export const UPDATE_ARTICLE_REQUEST = "UPDATE_ARTICLE_REQUEST";
export const UPDATE_ARTICLE_SUCCESS = "UPDATE_ARTICLE_SUCCESS";
export const UPDATE_ARTICLE_FAILED = "UPDATE_ARTICLE_FAILED";

